//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinPilot.Resources {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ThinkingMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ThinkingMessages() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WinPilot.Resources.ThinkingMessages", typeof(ThinkingMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cooking something....
        /// </summary>
        public static string Thinking1 {
            get {
                return ResourceManager.GetString("Thinking1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Compiling a brilliant idea....
        /// </summary>
        public static string Thinking10 {
            get {
                return ResourceManager.GetString("Thinking10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sharpening my neurons....
        /// </summary>
        public static string Thinking11 {
            get {
                return ResourceManager.GetString("Thinking11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Stretching logic muscles....
        /// </summary>
        public static string Thinking12 {
            get {
                return ResourceManager.GetString("Thinking12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Warming up the algorithms....
        /// </summary>
        public static string Thinking13 {
            get {
                return ResourceManager.GetString("Thinking13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Rebooting mental processor....
        /// </summary>
        public static string Thinking14 {
            get {
                return ResourceManager.GetString("Thinking14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Hacking into the matrix....
        /// </summary>
        public static string Thinking15 {
            get {
                return ResourceManager.GetString("Thinking15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Syncing brainwaves....
        /// </summary>
        public static string Thinking2 {
            get {
                return ResourceManager.GetString("Thinking2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Accessing deep knowledge....
        /// </summary>
        public static string Thinking3 {
            get {
                return ResourceManager.GetString("Thinking3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mixing smart stuff....
        /// </summary>
        public static string Thinking4 {
            get {
                return ResourceManager.GetString("Thinking4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Just a second....
        /// </summary>
        public static string Thinking5 {
            get {
                return ResourceManager.GetString("Thinking5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cranking the brain gears....
        /// </summary>
        public static string Thinking6 {
            get {
                return ResourceManager.GetString("Thinking6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Looking extremely wise right now....
        /// </summary>
        public static string Thinking7 {
            get {
                return ResourceManager.GetString("Thinking7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à AI magic in progress....
        /// </summary>
        public static string Thinking8 {
            get {
                return ResourceManager.GetString("Thinking8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Consulting the inner oracle....
        /// </summary>
        public static string Thinking9 {
            get {
                return ResourceManager.GetString("Thinking9", resourceCulture);
            }
        }
    }
}
